# Generated by Django 5.2.7 on 2026-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_case_taxmapping_and_casenumber_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Transaction Created'), ('case_update', 'Transaction Updated'), ('case_document_review', 'Transaction Document Reviewed'), ('case_remark', 'Transaction Remark Added'), ('case_status_change', 'Transaction Status Changed'), ('case_receipt', 'Transaction Physically Received'), ('case_assignment', 'Transaction Assigned'), ('case_approval', 'Transaction Approved'), ('case_rejection', 'Transaction Rejected'), ('case_release', 'Transaction Released'), ('support_feedback', 'Support Feedback Submitted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('in_review', 'In Review'), ('for_taxmapping', 'For Taxmapping'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('client_correction', 'Client Correction (30 days)'), ('returned', 'Returned (Legacy)'), ('withdrawn', 'Withdrawn')], default='not_received', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('lgu_admin', 'LGU Admin'), ('capitol_receiving', 'Receiver'), ('capitol_examiner', 'Examiner'), ('capitol_approver', 'Approver'), ('capitol_taxmapper', 'Tax Mapper'), ('capitol_numberer', 'Numberer'), ('capitol_releaser', 'Releaser')], max_length=50),
        ),
    ]
