# Generated by Django 5.2.7 on 2026-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_case_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('to_examine', 'To Examine'), ('in_review', 'Under Examination'), ('for_taxmapping', 'For Taxmapping'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('client_correction', 'Client Correction (30 days)'), ('returned', 'Returned (Legacy)'), ('withdrawn', 'Withdrawn')], default='not_received', max_length=20),
        ),
    ]
