# Generated by Django 5.2.7 on 2026-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGUTaxDeclarationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgu_name', models.CharField(choices=[('Alcantara', 'Alcantara'), ('Alcoy', 'Alcoy'), ('Alegria', 'Alegria'), ('Aloguinsan', 'Aloguinsan'), ('Argao', 'Argao'), ('Asturias', 'Asturias'), ('Badian', 'Badian'), ('Balamban', 'Balamban'), ('Bantayan', 'Bantayan'), ('Barili', 'Barili'), ('Boljoon', 'Boljoon'), ('Borbon', 'Borbon'), ('Carmen', 'Carmen'), ('Catmon', 'Catmon'), ('Compostela', 'Compostela'), ('Consolacion', 'Consolacion'), ('Cordova', 'Cordova'), ('Daanbantayan', 'Daanbantayan'), ('Dalaguete', 'Dalaguete'), ('Dumanjug', 'Dumanjug'), ('Ginatilan', 'Ginatilan'), ('Liloan', 'Liloan'), ('Madridejos', 'Madridejos'), ('Malabuyoc', 'Malabuyoc'), ('Medellin', 'Medellin'), ('Minglanilla', 'Minglanilla'), ('Moalboal', 'Moalboal'), ('Oslob', 'Oslob'), ('Pilar (Camotes)', 'Pilar (Camotes)'), ('Pinamungajan', 'Pinamungajan'), ('Poro (Camotes)', 'Poro (Camotes)'), ('Ronda', 'Ronda'), ('Samboan', 'Samboan'), ('San Fernando', 'San Fernando'), ('San Francisco (Camotes)', 'San Francisco (Camotes)'), ('San Remigio', 'San Remigio'), ('Santa Fe (Bantayan Island)', 'Santa Fe (Bantayan Island)'), ('Santander', 'Santander'), ('Sibonga', 'Sibonga'), ('Sogod', 'Sogod'), ('Tabogon', 'Tabogon'), ('Tabuelan', 'Tabuelan'), ('Tuburan', 'Tuburan'), ('Tudela (Camotes)', 'Tudela (Camotes)')], max_length=100, unique=True)),
                ('prefix', models.CharField(help_text="e.g., '120-' for Alcoy", max_length=10)),
                ('current_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='td_number',
            field=models.CharField(blank=True, help_text='Official Tax Declaration Number assigned by Numberer', max_length=50, null=True, unique=True),
        ),
    ]
