# Generated by Django 5.2.6 on 2026-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_lgutaxdeclarationsequence_case_td_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_format_preference',
            field=models.CharField(default='YYYY-MM-DD', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_critical_system_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_new_account_activations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_weekly_activity_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone_preference',
            field=models.CharField(default='Asia/Manila', max_length=64),
        ),
    ]
