# Generated by Django 5.2.6 on 2026-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_normalize_case_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Transaction Created'), ('case_update', 'Transaction Updated'), ('case_document_review', 'Transaction Document Reviewed'), ('case_remark', 'Transaction Remark Added'), ('case_status_change', 'Transaction Status Changed'), ('case_receipt', 'Transaction Physically Received'), ('case_assignment', 'Transaction Assigned'), ('case_approval', 'Transaction Approved'), ('case_rejection', 'Transaction Rejected'), ('case_numbered', 'Transaction Number Assigned'), ('case_release', 'Transaction Released'), ('support_feedback', 'Support Feedback Submitted')], max_length=50),
        ),
    ]
