# Generated by Django 5.2.6 on 2026-05-18

from typing import ClassVar

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0039_normalize_case_statuses"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="ArchivedCaseDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("doc_type", models.CharField(max_length=120)),
                ("file", models.FileField(max_length=1024, upload_to=core.models.archived_case_document_upload_to)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("keep_until", models.DateTimeField()),
                ("archived_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="archived_case_documents", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="archived_documents", to="core.case")),
            ],
            options={
                "ordering": ["-archived_at"],
            },
        ),
        migrations.AddIndex(
            model_name="archivedcasedocument",
            index=models.Index(fields=["case"], name="core_archiv_case_id_07c33d_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedcasedocument",
            index=models.Index(fields=["keep_until"], name="core_archiv_keep_un_5aa0d9_idx"),
        ),
    ]
