# Generated by Django 5.2.6 on 2026-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_returned_by_approver',
            field=models.BooleanField(default=False, help_text='Whether the case was returned by Approver to Examiner'),
        ),
    ]
