# Generated by Django 5.2.6 on 2026-05-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_case_is_returned_by_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_returned_by_approver',
        ),
    ]
