# Generated by Django 5.2.6 on 2026-05-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_auditlog_action'),
        ('core', '0042_remove_case_is_returned_by_approver'),
    ]

    operations = [
    ]
