# Generated by Django 5.2.6 on 2026-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_documentversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
