# Generated by Django 5.2.6 on 2026-05-21 18:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_documentversion_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentversion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(max_length=1024, upload_to=core.models.archived_case_document_upload_to),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
