# Generated by Django 5.2.6 on 2026-05-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_documentversion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='claimed_by_contact',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='claimed_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
