# Generated by Django 5.2.6 on 2026-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_case_claimed_by_contact_case_claimed_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('sqm', 'Square Meters (sq.m.)'), ('ha', 'Hectares (ha.)')], default='sqm', help_text='Unit of measurement for the property area', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='area_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Numerical area of the property (e.g. 250.0000)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='classification',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('agricultural', 'Agricultural'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mineral', 'Mineral'), ('timberland', 'Timberland'), ('special', 'Special')], max_length=20, null=True),
        ),
    ]
