# Generated by Django 5.2.6 on 2026-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_case_area_unit_case_area_value_case_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='co_owners',
            field=models.TextField(blank=True, help_text='List of co-owners (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='corporation_name',
            field=models.CharField(blank=True, help_text='Company or corporation name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ownership_type',
            field=models.CharField(choices=[('single', 'Single Owner'), ('married', 'Married / Spouses'), ('corporation', 'Corporation'), ('others', 'Others')], default='single', help_text='Ownership classification of the property owner', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Full name of spouse (if Married/Spouses)', max_length=255, null=True),
        ),
    ]
