# Generated by Django 5.2.6 on 2026-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_case_co_owners_case_corporation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='ownership_type',
            field=models.CharField(choices=[('single', 'Single Owner'), ('married', 'Married / Spouses'), ('corporation', 'Corporation'), ('others', 'Co-ownership')], default='single', help_text='Ownership classification of the property owner', max_length=20),
        ),
    ]
